cli: Error type "brick" does not exist." on replace brick
When trying to perform replace-brick operation from the
ovirt-shell we get an error message

error: type "brick" does not exist.

Change-Id: Iff900ec7e7ea8ebde3914ac28e5f72b426cf6544
Bug-Url: https://bugzilla.redhat.com/923196
Signed-off-by: Ravi Nori <rnori@redhat.com>